/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 11/04/2021 17:31:53
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/

#ifndef __MX_DEVICE_H
#define __MX_DEVICE_H

/*---------------------------- Clock Configuration ---------------------------*/

#define MX_LSI_VALUE                            40000
#define MX_LSE_VALUE                            32768
#define MX_HSI_VALUE                            8000000
#define MX_HSE_VALUE                            8000000
#define MX_HSI14_VALUE                          14000000
#define MX_HSI48_VALUE                          48000000
#define MX_PLLCLKFreq_Value                     8000000
#define MX_PLLMCOFreq_Value                     4000000
#define MX_SYSCLKFreq_VALUE                     8000000
#define MX_HCLKFreq_Value                       8000000
#define MX_MCOFreq_Value                        8000000
#define MX_FCLKCortexFreq_Value                 8000000
#define MX_TimSysFreq_Value                     8000000
#define MX_AHBFreq_Value                        8000000
#define MX_APB1Freq_Value                       8000000
#define MX_APB1TimFreq_Value                    8000000
#define MX_ADCoutputFreq_Value                  14000000
#define MX_FLITFCLKFreq_Value                   8000000
#define MX_CECFreq_Value                        32786
#define MX_I2C1Freq_Value                       8000000
#define MX_I2SFreq_Value                        8000000
#define MX_USART1Freq_Value                     8000000
#define MX_USART2Freq_Value                     8000000
#define MX_RTCFreq_Value                        40000
#define MX_RTCHSEDivFreq_Value                  250000
#define MX_USBFreq_Value                        48000000
#define MX_WatchDogFreq_Value                   40000
#define MX_VCOOutput2Freq_Value                 4000000

/*-------------------------------- I2C1       --------------------------------*/

#define MX_I2C1                                 1

/* GPIO Configuration */

/* Pin PA9 */
#define MX_I2C1_SCL_GPIO_Speed                  GPIO_SPEED_FREQ_HIGH
#define MX_I2C1_SCL_Pin                         PA9
#define MX_I2C1_SCL_GPIOx                       GPIOA
#define MX_I2C1_SCL_GPIO_PuPdOD                 GPIO_PULLUP
#define MX_I2C1_SCL_GPIO_FMA9                   __NULL
#define MX_I2C1_SCL_Display                     I2C1_SCL
#define MX_I2C1_SCL_GPIO_Pin                    GPIO_PIN_9
#define MX_I2C1_SCL_GPIO_AF                     GPIO_AF4_I2C1
#define MX_I2C1_SCL_GPIO_Mode                   GPIO_MODE_AF_OD

/* Pin PA10 */
#define MX_I2C1_SDA_GPIO_Speed                  GPIO_SPEED_FREQ_HIGH
#define MX_I2C1_SDA_Pin                         PA10
#define MX_I2C1_SDA_GPIOx                       GPIOA
#define MX_I2C1_SDA_GPIO_FMA10                  __NULL
#define MX_I2C1_SDA_GPIO_PuPdOD                 GPIO_PULLUP
#define MX_I2C1_SDA_Display                     I2C1_SDA
#define MX_I2C1_SDA_GPIO_Pin                    GPIO_PIN_10
#define MX_I2C1_SDA_GPIO_AF                     GPIO_AF4_I2C1
#define MX_I2C1_SDA_GPIO_Mode                   GPIO_MODE_AF_OD

/*-------------------------------- SYS        --------------------------------*/

#define MX_SYS                                  1

/* GPIO Configuration */

/*-------------------------------- TIM14      --------------------------------*/

#define MX_TIM14                                1

/* GPIO Configuration */

/* NVIC Configuration */

/* NVIC TIM14_IRQn */
#define MX_TIM14_IRQn_interruptPremptionPriority 0
#define MX_TIM14_IRQn_Subriority                0

/*-------------------------------- USART1     --------------------------------*/

#define MX_USART1                               1

#define MX_USART1_VM                            VM_ASYNC

/* GPIO Configuration */

/* Pin PA2 */
#define MX_USART1_TX_GPIO_ModeDefaultPP         GPIO_MODE_AF_PP
#define MX_USART1_TX_GPIO_Speed                 GPIO_SPEED_FREQ_HIGH
#define MX_USART1_TX_Pin                        PA2
#define MX_USART1_TX_GPIOx                      GPIOA
#define MX_USART1_TX_GPIO_PuPd                  GPIO_NOPULL
#define MX_UART1_TX_Debug                       USART1_TX
#define MX_USART1_TX_GPIO_Pin                   GPIO_PIN_2
#define MX_USART1_TX_GPIO_AF                    GPIO_AF1_USART1

/* Pin PA3 */
#define MX_USART1_RX_GPIO_ModeDefaultPP         GPIO_MODE_AF_PP
#define MX_USART1_RX_GPIO_Speed                 GPIO_SPEED_FREQ_HIGH
#define MX_USART1_RX_Pin                        PA3
#define MX_USART1_RX_GPIOx                      GPIOA
#define MX_USART1_RX_GPIO_PuPd                  GPIO_NOPULL
#define MX_UART2_RX_Debug                       USART1_RX
#define MX_USART1_RX_GPIO_Pin                   GPIO_PIN_3
#define MX_USART1_RX_GPIO_AF                    GPIO_AF1_USART1

/*-------------------------------- NVIC       --------------------------------*/

#define MX_NVIC                                 1

/*-------------------------------- GPIO       --------------------------------*/

#define MX_GPIO                                 1

/* GPIO Configuration */

/* Pin PA6 */
#define MX_PA6_Pin                              PA6
#define MX_PA6_GPIOx                            GPIOA
#define MX_PA6_GPIO_PuPd                        GPIO_NOPULL
#define MX_Set_Key                              PA6
#define MX_PA6_GPIO_Pin                         GPIO_PIN_6
#define MX_PA6_GPIO_Mode                        GPIO_MODE_INPUT

/* Pin PA5 */
#define MX_PA5_Pin                              PA5
#define MX_PA5_GPIOx                            GPIOA
#define MX_PA5_GPIO_PuPd                        GPIO_NOPULL
#define MX_Down_Arrow_Key                       PA5
#define MX_PA5_GPIO_Pin                         GPIO_PIN_5
#define MX_PA5_GPIO_Mode                        GPIO_MODE_INPUT

/* Pin PA7 */
#define MX_PA7_Pin                              PA7
#define MX_PA7_GPIOx                            GPIOA
#define MX_PA7_GPIO_PuPd                        GPIO_NOPULL
#define MX_Up_Arrow_Key                         PA7
#define MX_PA7_GPIO_Pin                         GPIO_PIN_7
#define MX_PA7_GPIO_Mode                        GPIO_MODE_INPUT

/* Pin PB1 */
#define MX_PB1_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PB1_Pin                              PB1
#define MX_PB1_GPIOx                            GPIOB
#define MX_PB1_PinState                         GPIO_PIN_RESET
#define MX_PB1_GPIO_PuPd                        GPIO_NOPULL
#define MX_Relay_Output                         PB1
#define MX_PB1_GPIO_Pin                         GPIO_PIN_1
#define MX_PB1_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

#endif  /* __MX_DEVICE_H */
